### ISSUE TITLE
make `CreateIssuePageJob` more generic

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/iiif_print#11]
# Summary

[CreateIssuePageJob](https://github.com/scientist-softserv/iiif_print/blob/main/app/jobs/iiif_print/create_issue_pages_job.rb) should be more generic. 

class method that should take an argument of what type of class it should split it into. ie `#split_pdf_into("Book")`

Currently the newspaper gem doesn't give you a choice. All created children are type `NewspaperPage`. 

ref: https://github.com/samvera-labs/newspaper_works/blob/bbe8736b0cf622d9c2577faf7a6f0a4e8dd1452c/lib/newspaper_works/ingest/newspaper_issue_ingest.rb#L41

# Acceptance Criteria
- [ ] `CreateIssuePageJob` is more generic
- [ ] `#split_pdf_into` takes an argument of a work type

**Comment by ShanaLMoore** [comment]
maybe reference and compare it to CreatePdftoJpg job in LV.

**Comment by laritakr** [comment]
Test comment for @ShanaLMoore

**Comment by laritakr** [comment]
Note: Per discussion at 12/14 standup, this job will be based on the Newspaper gem's job, where one or more PDFs are added to a parent work, and processing will split each PDF into individual works with multiple FileSets for each page of the PDF.

**Comment by jillpe** [comment]
#32 depends on this ticket

**Comment by ShanaLMoore** [comment]
TODO: Question about tiffs

change tiffs to jpgs for now. We will revisit this when we have Rob's attention

**Comment by laritakr** [comment]
See testing details on https://github.com/scientist-softserv/iiif_print/pull/83

**Comment by ShanaLMoore** [comment]
@laritakr did this get QA'd? I see it moved to this column but don't see notes detailing the results.

**Comment by laritakr** [comment]
Kirk and I did some ourselves, but neither of us added notes. Jeremy merged
it yesterday because it had code we needed for spec work, which is why I
moved it, but you're right that additional QA with notes is probably
beneficial.

*LaRita Robinson*

Senior Software Engineer | Software Services by Scientist.com
505 Lomas Santa Fe Dr.  l Ste. 110 l Solana Beach, CA  l 92075

LinkedIn <https://www.linkedin.com/in/laritakr/>
All correspondence and negotiations are subject to contract. Unless
otherwise noted, all information in this email and/or attachment is
strictly confidential and cannot be distributed externally without the
express written consent of Scientist.com.

**Comment by laritakr** [comment]
[Test with one PDF](https://qa.hyku-iiif.notch8.cloud/concern/generic_works/e341f3a7-c158-4208-8054-12c1fcf5061a?locale=en)
[Test work with multiple PDFs](https://qa.hyku-iiif.notch8.cloud/concern/generic_works/63ecf031-080e-4881-a2da-f7b95dea227e?locale=en)
