### ISSUE TITLE
Spike: Child works split from PDFs should create OCR derivatives

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/iiif_print#124]
Kirk's observation: 

When child works are created from the Split PDF feature, do the child works have OCR? 

If not, create a ticket for implementation

**Comment by kirkkwang** [comment]
## Findings

If the `pdf_split_child_model` is configured to anything other than `self` such as:

```rb
class Image < ActiveFedora::Base
  include IiifPrint.model_configuration(
    pdf_split_child_model: GenericWork
  )
end
```
Then the specified work type also needs to have ` IiifPrint.model_configuration` mixed in as well.

```rb
class Image < ActiveFedora::Base
  include IiifPrint.model_configuration
end
```
So in this scenario, if an `Image` is created with a multipage PDF, the PDF will be split up and the resulting child works will be `GenericWork` work types.  Since the `GenericWork` model also has `include IiifPrint.model_configuration`, the new child works to run OCR.
