### ISSUE TITLE
Install iiif_print into Essi

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/iiif_print#135]
# Summary 

Essi is a Hyrax app. This ticket serves two purposes. 

- [x] Test generator on a hyrax app
- [x] Install iiif_print into Indiana

# Acceptance Criteria

- [x] Indiana should have iiif_print installed. 
- [ ] ideally iiif_print should be fully functional, but depending on the level of effort for such configurations, this may be separated into its own ticket. Ref: Features List #66 

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by ShanaLMoore** [comment]
Will they need to upgrade their [bulkrax](https://github.com/IU-Libraries-Joint-Development/essi/blob/main/Gemfile.lock#L186) from 1.0.2 to 5.0?

**Comment by jillpe** [comment]
Timebox 4 hours

**Comment by kirkkwang** [comment]
# IIIF Dependencies
| Status | Package      | Essi      | IIIF Print |
| ------ | :----------- | :-------- | :--------- |
| ✅     | Fits         | 1.5.5     | 1.5.5      |
| ⚠️       | Tesseract    | 4.1.1     | 4.1.3      |
| ⚠️       | LibreOffice  | 7.0.4.2   | 7.2.7.2    |
| ✅     | GhostScript* | 9.53.3    | n/a        |
| ❌     | popper-utils | n/a       | 21.11.0    |
| ❌     | ImageMagick  | 6.9.11-60 | 7.1.0-57   |
| ⚠️       | libcurl3     | 7.74.0    | 7.80.0     |
| ⚠️       | libgbm1**    | n/a       | n/a        |

\* Does not have but is listed as a dependency

\*\* I could not find the version

# UI test

## Parent work to child work relation
Seems to be working, you can only see the child work in the UV and not the `_items` partial.

## Errors seen:
`convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421.`

This likely contributed to why the PDF derivative was not created correctly, file seems malformed and PDF splitting does not work.
**Ref:** https://github.com/scientist-softserv/iiif_print/blob/main/lib/iiif_print/image_tool.rb#L79

OCR text is not getting picked up.  The `txt`, `json`, and `xml` do get created but with no text.  When running tesseract in the container, it does seem to work though.

# Bulkrax test
We tested a Bulkrax import and it looks like at the moment we do not need to upgrade Bulkrax.

***** INCLUDE CSV HERE *****

# NOTE
Essi has their own text extraction that saves the output to `solr_doc['word_boundary_tsi'] `
Ref: https://github.com/scientist-softserv/essi/blob/main/app/indexers/essi/file_set_indexer.rb#L13

This instantiates this object https://github.com/scientist-softserv/essi/blob/main/lib/newspaper_works/text_extraction/alto_reader.rb

Which is effectively the same thing as https://github.com/scientist-softserv/iiif_print/blob/main/lib/iiif_print/text_extraction/alto_reader.rb

```sh
diff essi/lib/newspaper_works/text_extraction/alto_reader.rb essi/vendor/engines/iiif_print/lib/iiif_print/text_extraction/alto_reader.rb
5c5
< module NewspaperWorks
---
> module IiifPrint
42c42
<           match = attrs.select { |e| e[0].casecmp?('WIDTH') }[0]
---
>           match = attrs.find { |e| e[0].casecmp?('WIDTH') }
115,118c115,119
<         builder = NewspaperWorks::TextExtraction::WordCoordsBuilder.new(words,
<                                                                         @image_width,
<                                                                         @image_height)
<         builder.to_json
---
>         IiifPrint::TextExtraction::WordCoordsBuilder.json_coordinates_for(
>           words: words,
>           width: @image_width,
>           height: @image_height
>         )
```

Essi has a bunch of NewspaperWorks code (but did not install the gem) sprinkled throughout the codebase, likely because they didn’t need the entire gem and only a few features like Alto OCR.

# MISC
Potential bug in, worth a quick look:
```rb
Hyrax::Actors::CreateWithFilesOrderedMembersActor.prepend Extensions::Hyrax::Actors::CreateWithFilesOrderedMembersActor::AttachFilesWithMetadata
```
Ref: https://github.com/IU-Libraries-Joint-Development/essi/blob/eb1c9b652f1b96eda0eb65655d9b70e68bfe5042/app/actors/essi/actors/create_with_remote_files_ordered_members_structure_actor.rb#L1

**Comment by kirkkwang** [comment]
Closing this ticket because of break out tickets: #150, #151, #152, #153, #154, #155
