### ISSUE TITLE
Iiif child works show in "Recent Works"

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/iiif_print#187]
British Library requested that IiifPrint child works not appear in the Recent Additions feed. See https://github.com/scientist-softserv/britishlibrary/issues/303

When viewing the home page, the `Recent Works` section does include the child works. However when clicking `View All Recent Additions`, the child works are not included. 

**Expected Behavior:**
- [ ] These sections should **both** be using custom search builders to show only parent works.

**Screenshots:**
<details>
**Recent Works on Home Page**

![Image](https://user-images.githubusercontent.com/17851674/225458323-76989f18-c42b-40b0-971e-7b4f7bedced2.png)

**Recent Additions**

![Image](https://user-images.githubusercontent.com/17851674/225458350-f87d434e-cba6-4e66-a93c-c0a6db00b0e1.png)
</details>

# Testing Instructions

- [ ] Create a work with attached PDF to split into child works.
- [ ] Verify that only new parent work appears in Recent Works section of homepage.
- [ ] Wait 10 minutes for all jobs to finish. The relationship job has to complete on Sidekiq for the child works to disappear from the `Recent works` feed.

**Comment by laritakr** [comment]
To test:

- [ ] Create a work with attached PDF to split into child works. 
- [ ] Verify that only new parent work appears in Recent Works section of homepage.

**Comment by laritakr** [comment]
Can be tested via [BL](https://github.com/scientist-softserv/britishlibrary/pull/346) or [Adventist](https://github.com/scientist-softserv/adventist-dl/pull/324) once they are merged & deployed to staging.

**Comment by ShanaLMoore** [comment]
cc @laritakr Could you confirm if this has been deployed? ie: test it in BL or Adventist's staging. 

If so, please move this ticket to the QA column. If not, I assume we'd need a ticket to upgrade iiif_print for those projects?

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- parent work: https://bl.bl-staging.notch8.cloud/concern/books/c10593d8-5af2-4098-a3d5-0fa9f695b8ac?locale=en

<details><summary>A parent PDF's child works show up in the "Items" section of its work show page. These children do not show up on the "Recent works" feed on the home page.</summary>

![Book 2023-04-05 #187 ID c10593d8-5af2-4098-a3d5-0fa9f695b8ac Hyku 2023-04-05 at 10 36 20 AM](https://user-images.githubusercontent.com/29311858/230160113-a84298fe-b385-4f21-9b7e-25554906fb1c.jpg)
![BL Staging 2023-04-05 at 10 36 34 AM](https://user-images.githubusercontent.com/29311858/230160137-a010888b-37ae-4c9a-ae34-e77339124406.jpg)

</details>

**Comment by grahamjevon** [comment]
This does **not** pass BL QA as the recent works section is displaying the split page child works of a pdf. See screenshot below. (This work was added more than 12 hours ago, so the relationship job should have been completed).

![Image](https://user-images.githubusercontent.com/51366817/231676213-2d2a9135-8d02-48ef-9213-e80bca944052.png)

It also does not pass QA because the Recent Additions feed and the generic Search Results feed are also displaying split page child works of a pdf:

![Image](https://user-images.githubusercontent.com/51366817/231677451-c6ccf46c-d974-42d5-99ec-f825441e5943.png)

It looks like these child works might all come from a pdf that was uploaded when editing a work (as opposed to uploading at the point of adding a work).

**Comment by jillpe** [comment]
BL's findings: https://assaydepot.slack.com/archives/C0313NK2LJ0/p1681316986158039

**Comment by grahamjevon** [comment]
The delay in removing split pdf child works from the recent works feed is too long. When uploading only a 2 page pdf, the child works appear in the recent additions field for approximately 10 minutes. When uploading a pdf book, the child works can clog up the recent additions feed for more than 1 hour.

![Image](https://user-images.githubusercontent.com/51366817/232736723-8524c826-70c2-4a27-b2dd-3370ca960576.png)

While a slow upload and slow splitting of pdfs is not a problem in itself, this is a problem when it impacts other parts of the site. If a member of the public visits the repository while a pdf is uploaded and sees a recent additions field clogged with things that we don't want to appear there, they won't know this is because of background uploading processes. This will not be a good first impression of the site.

We discussed before having a separate "page" resource type for these split pdf works. If these child works had such a unique resource type, could that be used to prevent these works from ever appearing in the recent works feed? (so that we can avoid having to wait for background relationship jobs to complete in order to remove them).

**Comment by laritakr** [comment]
Until these split works are attached to a parent, they are not "child works" as far as the system knows. A unique resource type that is totally eliminated from showing in searches would definitely be one option. We would need to brainstorm other options..

**Comment by laritakr** [comment]
Creating a new ticket to address this issue with a new child work type so we can close this one. This work is completed in iiif_print. Remaining ticket addresses additional behavior requests for British Library. 

https://github.com/scientist-softserv/britishlibrary/issues/387
