### ISSUE TITLE
🐛 IiifPrint does not split or create relationships

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/iiif_print#343]
IiifPrint is not splitting appropriately. The purpose of this ticket is to handle PDFs appropriately.

Ref https://github.com/scientist-softserv/iiif_print/issues/341

## Acceptance Criteria

On a properly configured tenant & work,
- [ ] A work with PDF uploaded through the UI will split & display in UV
- [ ] A work with PDF uploaded through Bulkrax will split & display in UV
- [ ] Child works connect appropriately to the parent work
- [ ] A PDF can be resplit via a button on the file view
- [ ] When a PDF is removed, the derived child works also are removed

**Comment by laritakr** [comment]
Currently blocked by https://github.com/samvera/hyku/issues/2177

**Comment by ShanaLMoore** [comment]
TODO: Update IiifPrint in Hyku

**Comment by jillpe** [comment]
Blocked: Waiting to be updated in hyku

**Comment by laritakr** [comment]
https://github.com/samvera/hyku/pull/2210

**Comment by ShanaLMoore** [comment]
# QA RESULTS: PENDING

**Comment by ShanaLMoore** [comment]
# QA RESULTS: PASS ✅ 

Tested on [HYKU STAGING](https://demo.hyku-staging.notch8.cloud/concern/generic_works/d83006a9-42cf-4d7e-91d9-82e6fb8747a7?locale=en)

I manually imported a multi page pdf. Set the feature flag to us UV instead of PDF.js. It correctly split the PDF: 



![Image](https://github.com/scientist-softserv/iiif_print/assets/10081604/a711ba12-d6a7-4df1-b3ca-059b547c2171)
