### ISSUE TITLE
IIIF Print's permissions should propagate down to its children

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/iiif_print#347]
# Summary

Timebox: 8hrs

![Image](https://github.com/scientist-softserv/iiif_print/assets/10081604/752ef4a3-abdd-40c2-8234-43f2b01fcd45)

# Acceptance Criteria

- [ ] If a parent work has visibility or permission rules declared, those rules should be propagated down to its child works. 
- [ ] update iiif print's hyku

# Screenshots or Video

# Testing Instructions

# Notes

Look into Hyrax Propagator service as an option. And/or adding the new properties in iiif print (but is it readable?) 

https://github.com/samvera/bulkrax/pull/950

**Comment by ShanaLMoore** [comment]
TODO: merge split work in so that we can test this.

**Comment by ShanaLMoore** [comment]
TODO: Test via Bulkrax and UI

**Comment by jillpe** [comment]
QA blocked until it is updated in the knapsack apps

**Comment by ShanaLMoore** [comment]
# QA RESULTS: PENDING

**Comment by jillpe** [comment]
To Do:
- Try manual work creation with the multi-page pdf

**Comment by ShanaLMoore** [comment]
# QA RESULTS: Pending ⚠ 

Manually tested on [Hyku STAGING](https://demo.hyku-staging.notch8.cloud/concern/generic_works/d83006a9-42cf-4d7e-91d9-82e6fb8747a7?locale=en)

cc @laritakr does this look right to you?

The work successfully split, but it seems like it split multiple times. 

I was expecting to see 1 -page 1, and 1 -page 2 but I see 2 of each with a slightly different title. 

UPDATE: The latter two are file sets so maybe we create a separate ticket to hide them.

![Image](https://github.com/scientist-softserv/iiif_print/assets/10081604/53aecd34-4a21-4d0b-8bf3-31cd40579478)

Besides that, clicking into the child works correctly maintains the embargo dates of the parent work. However one of the child file sets says Private when they should all say Embargo. 

## PARENT



![Image](https://github.com/scientist-softserv/iiif_print/assets/10081604/f72a97cb-2951-4ebc-94ff-7744f269036a)

## CHILD WORKS



![Image](https://github.com/scientist-softserv/iiif_print/assets/10081604/a95a678e-b7a5-49e8-be52-447210edec45)



![Image](https://github.com/scientist-softserv/iiif_print/assets/10081604/23885216-b84e-49f1-b077-a4112a798596)


## FILE SETS



![Image](https://github.com/scientist-softserv/iiif_print/assets/10081604/282e93ee-fb42-42da-b622-d5c6aeac296d)



![Image](https://github.com/scientist-softserv/iiif_print/assets/10081604/6368beaa-301b-45bd-8692-a640d31d8a46)

**Comment by laritakr** [comment]
Yes, the file sets showing in the list are, I believe, due to some change in Hyrax. [I filed a bug ticket for it a while back.](https://github.com/samvera/hyrax/issues/6767)

The file set not getting lease/embargo I believe also comes from Hyrax. There may have been a failure in the job that propagates the permission from the child work to the fileset. However I don't consider it a serious problem because

1. the fallback visibility is the parent work's current visibility so you can only see it if you are authorized to the parent (it falls back to the visibility before the expiry date)
2. when the lease or embargo is expired, the job will still find and change the visibility correctly
